import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { SafeAuthKit, SafeAuthProviderType } from "@safe-global/auth-kit";
import Login from "@/components/Login";
import Logout from "@/components/Logout";

export default function Home() {
    return (
        <>
            <Head>
                <title>Gumnaam</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Login />
            <Logout />
            <main className={styles.main}>Hello World</main>
        </>
    );
}
