import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { SafeAuthKit, SafeAuthProviderType } from "@safe-global/auth-kit";
import Login from "@/components/Login";
import Logout from "@/components/Logout";
import { AppContainer } from "@/components/AppContainer";
import SafeAuthContext from "@/contexts/SafeAuthContext";
import { useContext } from "react";

export default function Home() {
    const ctx = useContext(SafeAuthContext);
    return (
        <AppContainer>
            <Head>
                <title>Gumnaam</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Login />
            <Logout />
            <button onClick={() => console.log(ctx)}>Log Context</button>
            <main className={styles.main}>Hello World</main>
        </AppContainer>
    );
}
